// @ts-check
// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The documentation migration handbook sidebar.
 *
 * Explicit, not autogenerated. The order of these pages is an editorial
 * decision about the order the work happens in, and a page should not enter the
 * navigation just because a file landed in a directory - adding one here is the
 * review step. Each category links to a generated index, so a category heading
 * is a real destination instead of a dead click.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  handbookSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Planning',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/planning',
        title: 'Planning a documentation migration',
        description:
          'Decide whether a migration is worth doing, inventory what you have, and scope the work before anything moves.',
      },
      items: [
        'planning/deciding-whether-to-migrate',
        'planning/content-inventory',
        'planning/scoping-and-sequencing',
        'planning/stakeholder-buy-in',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/architecture',
        title: 'Documentation architecture',
        description:
          'Define content types, navigation, naming rules and versioning before you move a page, so the structure survives product change.',
      },
      items: [
        'architecture/content-types-and-templates',
        'architecture/navigation-models',
        'architecture/naming-and-vocabulary',
        'architecture/versioning-strategies',
      ],
    },
    {
      type: 'category',
      label: 'Migration',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/migration',
        title: 'Running the migration',
        description:
          'Convert content to clean Markdown, move images and attachments, map every old URL to a new one, and prove the result is correct before you cut over.',
      },
      items: [
        'migration/converting-to-markdown',
        'migration/images-and-attachments',
        'migration/redirect-mapping',
        'migration/qa-and-link-checking',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      collapsed: false,
      link: {
        type: 'generated-index',
        slug: '/operations',
        title: 'Operating documentation after launch',
        description:
          'Publishing pipelines, review gates, authoring standards and an ownership model, so the documentation stays accurate after the migration team moves on.',
      },
      items: [
        'operations/ci-cd-publishing',
        'operations/review-gates',
        'operations/authoring-standards',
        'operations/ownership-and-governance',
      ],
    },
  ],
};

export default sidebars;
